name: Deploying My Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Kotlin Project
    runs-on: ubuntu-latest

    steps:
      # - name: Debug
      #   run: echo ${{ secrets.EMAIL }}| sed 's/./& /g'
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: List APKs
        run: ls -R app/build/outputs/apk

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: app/build/outputs/apk/debug

      # - uses: cinotify/github-action@main
      #   with:
      #     to: ${{ secrets.USER}}
      #     subject: 'A TEST NOTIFICATION'
      #     body: '<em>This is a notification from GitHub actions.</em>'
      #     type: 'text/html'
      #     attachment: 'app/build/outputs/apk/debug/app-debug.apk'

      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
         host: smtp.google.com
         account: ${{secrets.USER}}
         password: ${{secrets.PASS}}
         sender: devellany
         from: ${{secrets.USER}}
         to: ${{secrets.EMAIL_TO}}
         subject: mail title.
         contentType: text/html
         attachments: app/build/outputs/apk/debug/app-debug.apk

