name: Deploying My Build

on:
  push:
    tags:
      - '*'           # any tag
    branches:
      - main

jobs:
  build:
    name: Build Kotlin Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Show build output files
        run: ls -R build/


      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-build
          path: build/libs/   # or wherever your build outputs are

