name: Deploying My Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Kotlin Project
    runs-on: ubuntu-latest

    steps:
      # - name: Debug
      #   run: echo ${{ secrets.EMAIL }}| sed 's/./& /g'
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: List APKs
        run: ls -R app/build/outputs/apk

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: app/build/outputs/apk/debug

      # - uses: cinotify/github-action@main
      #   with:
      #     to: ${{ secrets.USER}}
      #     subject: 'A TEST NOTIFICATION'
      #     body: '<em>This is a notification from GitHub actions.</em>'
      #     type: 'text/html'
      #     attachment: 'app/build/outputs/apk/debug/app-debug.apk'

      - name: Send mail
        uses: betterfor/action-send-mail@main
        with:
          # Reqired mail server address 
          server_address: smtp.qq.com
          # Optional Server port, default 25 (if server_port is 465 this connection use TLS)
          server_port: 465
          # # Optional (recommended): mail server username
          # username: ${{secrets.MAIL_USERNAME}}
          # # Optional (recommended): mail server password
          # password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject
          subject: Github Actions job results
          # Required recipients address
          to: dwardy0101@gmail.com
          # Required sender full name (address can be skipped)
          from: ${{secrets.USER}}
          # Optional plain body
          body: Build job of ${{github.repository}} completed successfully!
          # # Optional HTML body read from file
          # html_body: file://README.md
          # # Optional carbon copy recipients
          # cc: a@example.com,b@example.com
          # # Optional blind carbon copy recipients
          # bcc: c@example.com,d@example.com
          # # Optional recipient of the email response
          # reply_to: luke@example.com
          # # Optional Message ID this message is replying to
          # in_reply_to: <random-luke@example.com>
          # # Optional converting Markdown to HTML (set content_type to text/html too)
          # convert_mardown: true
          # Optional attachments
          attachments: app/build/outputs/apk/debug/app-debug.apk
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: high
